name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8
    - name: Run autopep8 (fix formatting issues)
      run: |
        # See and fix all Python formatting issues
        autopep8 --in-place --recursive .
    - name: Run Linter
      run: |
        # This command runs Flake8 to find linting issues
        flake8
        echo "Linted all the Python files successfully."

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install JSHint
      run: npm install jshint --global
    - name: Run Linter
      run: |
        # Find and lint all JavaScript files
        find ./server/database -name "*.js" -exec jshint {} +
        echo "Linted all the JavaScript files successfully."
